name: CI Build BT-Panel Base Centos7

on: [push]

env:
  ssh_enabled: false
  IMAGE_NAME: bt-panel
  IMAGE_VERISON: H_lnpwpf

jobs:
  build:
    runs-on: ubuntu-latest

    - name: Checkout
      uses: actions/checkout@master
    
    - name: SSH connection
      uses: mxschmitt/action-tmate@v2
      if: env.ssh_enabled == 'true'
    
    - name: Build image
      run: bash ./build.sh
    
      - name: Login registry
      run: echo "${{ secrets.DockerHub_Password }}" | docker login -u ${{ secrets.DockerHub_Useranme }} --password-stdin

    - name: Push image
      run: docker push ftd5x/bt-panel:H_lnp_wpf
