name: CI Build BT-Panel Base Centos7

on: [push]



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configura
      run: echo '{ "experimental":true}'> /etc/docker/daemon.json && systemctl restart docker
      
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Build image
      env:
        IMAGE_ANME: BT-Panel
        IMAGE_VERISON: clear
      run: docker build . --file Dockerfile --tag ${{ secrets.DockerHub_Useranme }}/$IMAGE_NAME:$IMAGE_VERISON --squash
    - name: Login registry
      run: echo "${{ secrets.DockerHub_Password }}" | docker login -u ${{ secrets.DockerHub_Useranme }} --password-stdin

    - name: Push image
      env:
        IMAGE_ANME: BT-Panel
        IMAGE_VERISON: clear
      run: docker push ${{ secrets.DockerHub_Useranme }}/$IMAGE_NAME:$IMAGE_VERISON
